### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by nelstrom** [djmoch/vim-makejob#12]
Would you be open to accepting a pull request that adds support for [Neovim](https://neovim.io/)?

**Comment by djmoch** [comment]
Let's talk about it. 

If you look at the v0.1 tag, I actually wrote the initial PoC against Neovim. I don't think there would be a ton of work involved in bringing it back and merging it in alongside the Vim code. 

If I have any misgivings, it's that I'm not interested in personally taking on maintenance of the Neovim code. I don't use Neovim anymore, and so I just have no way to test it. I guess that's not a deal breaker; it just means I won't be the one fixing problems with the Neovim code.

**Comment by nelstrom** [comment]
I didn't realise that you had originally built this plugin for Neovim. Studying your [v0.1 proof-of-concept](https://github.com/djmoch/vim-makejob/blob/v0.1/plugin/makejob.vim) I can see what you mean. I understand your reluctance to support Neovim if you no longer use it yourself, but thanks for being open to discussion!

What do you think about using [async.vim](https://github.com/prabirshrestha/async.vim)? [This discussion on minpac](https://github.com/k-takata/minpac/issues/3) is relevant.

**Comment by djmoch** [comment]
This seems like a good idea, but I'm pretty firmly against creating a dependency since there's just no easy way to manage it. So we'll have to copy the async.vim code into MakeJob in addition to refactoring to use its API. 

Reading between the lines in the minpac discussion, it sounds like @prabirshrestha will be okay with us distributing his code with MakeJob, but I'll tag him here in case he thinks otherwise.

**Comment by prabirshrestha** [comment]
Feel free to embed async.vim. Unfortunately it needs to be a copy since embeders shouldn't use `async#job#func_name` and should be `vimmakejob#job#func_name`.
It would be interesting if we can get git subtree working with patches to rename functions so it could be automated.

Another approach is take dependency on async.vim. I have done this for some of the asyncomplete plugins I have written.

https://github.com/prabirshrestha/asyncomplete-gocode.vim#installing
https://github.com/prabirshrestha/asyncomplete-flow.vim#installing

```vim
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-gocode.vim'
```

**Comment by djmoch** [comment]
> Feel free to embed async.vim.
> 
Thanks! I'm aware that I'll need update the autoload namespace to avoid conflicts. I'll be careful to do that. 
> Another approach is take dependency on async.vim. 
> 
Despite my strong language earlier, a big part of me wishes I could do this. Unfortunately there's no standard way of doing this in (Neo)Vim and so users are left to work out the dependency management themselves. I'm not okay with that. 

One thought I had would be to detect dynamically whether we were running in Vim or Neovim, and in the latter case checking for the existence of async.vim (we could fall back to the current code if running in Vim). If async isn't there, then we can display an error. Users would still be stuck managing the dependencies, but it at least allows us to make some hints when required dependencies aren't present.

**Comment by djmoch** [comment]
I consider this a long-overdue update. 

Looking at async.vim, MakeJob will essentially have to be re-written in order to incorporate it. This is because async hews closer to the NeoVim API for job management, whereas I’m using the (in my opinion more mature) Vim8 API. I just don’t have the time to invest in that kind of effort at this point. 

I’ll leave this open, and I’ve tagged it indicating that others are welcome to submit pull requests. Beyond that, I can’t commit to a timeline.

**Comment by djmoch** [comment]
Moving development over to my [personal Git server](https://git.danielmoch.com). This issue will live on there and pull requests are still welcome per the process laid out in the README.
