### ISSUE TITLE
not adding output to quickfix/loclist windows

### ISSUE THREAD

**Issue by s-ol** [djmoch/vim-makejob#5]
hm, next problem; running asynchroneously works but I don't get any output/error reporting. It works fine with `:make`.

**Comment by djmoch** [comment]
I'm not able to reproduce. You're saying the findings aren't being populated in the Quickfix/Location List windows? Keep in mind that you're not going to see _all_ of the output there, just a filtered list of lines that have a match in `&errorformat`. Looking though the docs, that does not appear to be the way `:make` behaves, so I should probably adjust. Is it possible that's what's going on here?

**Comment by s-ol** [comment]
@djmoch when I `:make` it shows me a bunch of lines, some highlighted (that's the ones matching the errorfmt I believe?). When I do `:MakeJob` under the exact same circumstances it says `make ended with 0 findings`.

**Comment by djmoch** [comment]
Okay, so it sounds like that's at least a part of the problem.

Separate question, could you send me your makeprg?

**Comment by s-ol** [comment]
it's just 'make' in a simple C++ cmake project. The errorformat is from `:compiler gcc`:

`errorformat=%*[^"]"%f"%*\D%l: %m,"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file incl
uded from %f:%l:%c:,%-GIn file included from %f:%l:%c\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[
 ]from %f:%l\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,"%f"\, line %l%*\D%c%*[^ ] %m,%D%*\a[%*\d]: Entering directory %*[`']%f',%X%*\a[%*\d]: Leaving directory
 %*[`']%f',%D%*\a: Entering directory %*[`']%f',%X%*\a: Leaving directory %*[`']%f',%DMaking %*\a in %f,%f|%l| %m`

**Comment by djmoch** [comment]
Okay. I was wondering if my code converting makeprg to a list was broken, but that's not likely if you're just running make.

I'll take out the filtering when I'm back at my machine. Can you let me know if that fixes your issue?

**Comment by djmoch** [comment]
Can you see if 006b0bba81f6d8a36724f57d9ec540afdfe8ae66 fixes your issue?

**Comment by s-ol** [comment]
nope, nothing still. Could this be some interference from w0rp/ale?

**Comment by djmoch** [comment]
It could be. I ran some tests using both `:make` and `:MakeJob` and found that, while they behaved the same as each other, they were similarly inconsistent across multiple runs with `compiler gcc`. I figured this made sense since, depending on your Makefile, you're probably not running `make clean` every time you build, and so you won't see the same results. All that to say, if w0rp/ale is causing this issue, then I tend to think the real root cause lies elsewhere. 

Unfortunately I'm not really sure what to have you try next, unless you're willing to step through `s:JobHandler` and see if anything jumps out as obviously wrong. You could start by looking what's in the `output` list after it's done reading the channel.

**Comment by djmoch** [comment]
Just added handling of `stderr`. Let me know if that fixes your issue.

**Comment by s-ol** [comment]
oh wow, it really was that simple. Nice!

**Comment by djmoch** [comment]
Fixed with eb87bb0e4ce7e148c371c7d35102eedeec242871
